### ISSUE TITLE
connect issue tracker

### ISSUE THREAD

**Issue by heyjay44** [fireproof-storage/connect#129]
- [ ] gather all gateways and there server implementation in one repo and use mock implementation for the test suite self depending) plus CI.
- [ ] enable the production deployment of all server components from the CI
- [ ] make series0.20 branch working with main of core (meno)
- [ ]  run the core test suite against all gateways.
- [ ] interop and scale test suite which features a main controller which controllers seed against which allow to remotely start n instances of a specific configuration from the main controller. An the main controller allow to  push the connect graph to all connected instances. in addition the main controller can control every instance remotely get/put/query/alllDocs and set or get data with meta data like timing for the operations.
- [ ]  libp2p gateway 
- [ ] meta key simple key merging protocol
